# Generated by Django 5.2.1 on 2025-05-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('domain', models.CharField(max_length=255, unique=True, verbose_name='Domain')),
                ('issued_at', models.DateField(verbose_name='Issued At')),
                ('expires_at', models.DateField(verbose_name='Expires At')),
                ('signature', models.TextField(verbose_name='Signature')),
            ],
        ),
    ]
