# Generated by Django 5.2.1 on 2025-05-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnipyx_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='accepted_terms',
            field=models.BooleanField(default=False, verbose_name='Accepted Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='license',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AddField(
            model_name='license',
            name='company_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Company Phone'),
        ),
        migrations.AddField(
            model_name='license',
            name='db_engine',
            field=models.CharField(default='django.db.backends.postgresql', max_length=100, verbose_name='Database Engine'),
        ),
        migrations.AddField(
            model_name='license',
            name='db_host',
            field=models.CharField(default='localhost', max_length=255, verbose_name='Database Host'),
        ),
        migrations.AddField(
            model_name='license',
            name='db_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Database Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='db_password',
            field=models.CharField(default=1, max_length=255, verbose_name='Database Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='db_port',
            field=models.CharField(default='5432', max_length=10, verbose_name='Database Port'),
        ),
        migrations.AddField(
            model_name='license',
            name='db_user',
            field=models.CharField(default=1, max_length=100, verbose_name='Database User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='license',
            name='enable_audit',
            field=models.BooleanField(default=True, verbose_name='Enable Audit Log'),
        ),
        migrations.AddField(
            model_name='license',
            name='license_type',
            field=models.CharField(default='full', max_length=50, verbose_name='License Type'),
        ),
        migrations.AddField(
            model_name='license',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Company Logo'),
        ),
        migrations.AddField(
            model_name='license',
            name='partner_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Partner Code'),
        ),
        migrations.AddField(
            model_name='license',
            name='preferred_language',
            field=models.CharField(default='en', max_length=10, verbose_name='Preferred Language'),
        ),
        migrations.AddField(
            model_name='license',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Timezone'),
        ),
    ]
